### ISSUE TITLE
Performance is not good enough on large fillomino problems

### ISSUE THREAD

**Issue by T0nyX1ang** [T0nyX1ang/noqx#17]
For large grids, the performance of current solver is degraded.

**Comment by T0nyX1ang** [comment]
The new methods can be somewhat faster, but there are edge cases for the original solvers and new solvers.
I added two examples to demonstrate the issue.

**Comment by T0nyX1ang** [comment]
After trying out some approaches, we decide to introduce a "fast mode" where the solutions will be restricted on a certain size.
- The numbers are taken from (1-5 + the given clues on board) to limit to solution space.

The method can work on all cases, and the worst case takes about 2.5x time over the original solver.

**Comment by T0nyX1ang** [comment]
Here is another edge case: <https://github.com/tomvbussel/fillomino/blob/master/problems/p76.fillomino>

We may assume that the solver will degrade when there are many long "snakes" in it.

**Comment by T0nyX1ang** [comment]
The same problem exists for heteromino puzzles.

**Comment by T0nyX1ang** [comment]
For a full analysis, solver is slow on large problems of:
- fillomino
- haisu
- kurotto
- shikaku

**Comment by T0nyX1ang** [comment]
shikaku problems have been greated optimized by latest commit af7bd76
haisu problems have been greatly optimized (but have some edge cases) by recent commit 3849683

**Comment by T0nyX1ang** [comment]
The edge case for fillomino becomes faster by recent commit 48ddc1b, by using `grid_src_color_connected` instead of `grid_branch_color_connected` in initial points.

**Comment by T0nyX1ang** [comment]
After some approaches, we decided to set the problem aside for a while.

**Comment by zhuyaoyu** [comment]
The Fillomino solver is greatly optimized by the recent commit  01eb054. The core statement is the following:
`rule += ":- grid(R, C), number(R, C, N1), number(R, C, N2), N1 < N2.\n"`
This is similar to the case in Haisu commit 2e05066.

**Comment by T0nyX1ang** [comment]
This is a very good approach in the optimization 01eb054, closing this issue now.
